export const categories = [
  { id: 27, value: "Animals" },
  { id: 26, value: "Celebrities" },
  { id: 16, value: "Entertainment: Board Games" },
  { id: 10, value: "Entertainment: Books" },
  { id: 32, value: "Entertainment: Cartoon & Animations" },
  { id: 29, value: "Entertainment: Comics" },
  { id: 11, value: "Entertainment: Film" },
  { id: 31, value: "Entertainment: Japanese Anime & Manga" },
  { id: 12, value: "Entertainment: Music" },
  { id: 14, value: "Entertainment: Television" },
  { id: 15, value: "Entertainment: Video Games" },
  { id: 9, value: "General Knowledge" },
  { id: 22, value: "Geography" },
  { id: 23, value: "History" },
  { id: 20, value: "Mythology" },
  { id: 24, value: "Politics" },
  { id: 18, value: "Science: Computers" },
  { id: 19, value: "Science: Mathematics" },
  { id: 17, value: "Science & Nature" },
  { id: 21, value: "Sports" },
  { id: 28, value: "Vehicles" },
];
